#+language: ru
#+latex_class: extreport
#+latex_class_options: [a4paper,12pt]
#+latex_header: \usepackage{fontspec}
#+latex_header: \usepackage[AUTO]{babel}
#+latex_header: \usepackage{indentfirst}
#+latex_header: \setmainfont{PT Astra Serif}
#+latex_header: \usepackage[margin=1.5cm]{geometry}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage{enumitem}
#+latex_header: \usepackage{unicode-math}
#+latex_header: \usepackage[math]{cellspace}

#+latex_header: \newtheorem{theorem}{Теорема}[section]
#+latex_header: \newtheorem{lemma}[theorem]{Лемма}
#+latex_header: \newtheorem{property}[theorem]{Свойство}

#+latex_header: \theoremstyle{definition}
#+latex_header: \newtheorem{definition}{Определение}[section]

#+latex_header: \newcommand{\newpar}{$ $\par\nobreak\ignorespaces}
#+latex_header: \renewenvironment{proof}{{\noindent\bfseries Доказательство.}}{\smallskip\newpar \hfill\textit{Что и требовалось доказать.}}

#+latex_header: \usepackage[x11names]{xcolor}
#+latex_header: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = PaleGreen1, linkcolor = black}

#+begin_export latex
\setlist[itemize]{itemsep=0.5em,topsep=0em,parsep=0em}
\setlist[enumerate]{itemsep=0.5em,topsep=0em,parsep=0em}

\hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = PaleGreen1, linkcolor = blue}

\makeatletter
\def\thm@space@setup{\thm@preskip=1pt
\thm@postskip=1pt}
\makeatother
#+end_export

#+begin_export latex
\def\lets{%
    \mathord{\setbox0=\hbox{$\exists$}%
             \hbox{\kern 0.125\wd0%
                   \vbox to \ht0{%
                      \hrule width 0.75\wd0%
                      \vfill%
                      \hrule width 0.75\wd0}%
                   \vrule height \ht0%
                   \kern 0.125\wd0}%
           }%
}
#+end_export


* Матрицы и определители
** Определения
#+begin_definition
Матрица размером \(m \times n\) — таблица выражений, состоящая из \(m\) строк и \(n\) столбцов:

\begin{equation*}
    \underset{m \times n}{A} =
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        a_{21} & a_{22} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{m1} & a_{m2} & \ldots & a_{mn}
    \end{pmatrix}
    = (a_{ij}).
\end{equation*}
#+end_definition

#+begin_definition
След матрицы — это сумма диагональных элементов матрицы. Операция взятия следа обозначается \(\mathrm{tr}\):
\begin{equation*}
    \underset{n \times n}{A} =
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        a_{21} & a_{22} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{n1} & a_{n2} & \ldots & a_{nn}
    \end{pmatrix};
    = (a_{ij})
    \qquad
    \mathrm{tr} A = \sum_{i = 1}^n = a_{11} + a_{22} + \ldots + a_{nn}
\end{equation*}
#+end_definition

#+begin_definition
Ранг матрицы — это наивысший порядок ненулевого минора. Ранг матрицы обозначается \(\mathrm{rang}\).
#+end_definition

** Виды матриц
В зависимости от размерности, матрицы имеют названия, приведенные в следующей таблице.
#+attr_latex: :align |c|c|c|c|
| Размерность | Название      | Размерность | Название        |
|-------------+---------------+-------------+-----------------|
| \(m \times n\)   | прямоугольная | \(1 \times n\)   | матрица-строка  |
| \(n \times n\)   | квадратная    | \(m \times 1\)   | матрица-столбец |

Элементы квадратной матрицы, имеющие одинаковые индексы (\(a_{11}\), \(a_{22}\), \(\ldots\), \(a_{nn}\)), образуют /главную диагональ матрицы/. Диагональ, соединяющая элементы \(a_{1n}\), \(a_{2n}\), \(\ldots\), \(a_{n1}\), называется /побочной диагональю матрицы/.

Квадратная матрица, у которой все элементы, расположенные выше (ниже) главной диагонали, равны нулю, называется /нижней/ (/верхней/) /треугольной матрицей/:
#+begin_export latex
\begin{equation*}
    \text{нижняя:}
    \quad
    \begin{pmatrix}
        a_{11} & 0 & \ldots & 0 \\
        a_{21} & a_{22} & \ldots & 0 \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{n1} & a_{n2} & \ldots & a_{nn}
    \end{pmatrix};
    \qquad \qquad
    \text{верхняя:}
    \quad
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        0      & a_{22} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        0      & 0 & \ldots & a_{nn}
    \end{pmatrix}
\end{equation*}
#+end_export

Квадратная матрица, имеющая ненулевые элементы только на главной диагонали, называется /диагональной/:
#+begin_export latex
\begin{equation*}
    \mathrm{diag} \{ a_{11}, a_{22}, \ldots, a_{nn} \} =
    \begin{pmatrix}
        a_{11} & 0 & \ldots & 0 \\
        0 & a_{22} & \ldots & 0 \\
        \ldots & \ldots & \ldots & \ldots \\
        0 & 0 & \ldots & a_{nn}
    \end{pmatrix}
\end{equation*}
#+end_export

Диагональная матрица, у которой все элементы главной диагонали равны единицам, называется /единичной/:
#+begin_export latex
\begin{equation*}
    \underset{n \times n}{I} =
    \begin{pmatrix}
        1 & 0 & \ldots & 0 \\
        0 & 1 & \ldots & 0 \\
        \ldots & \ldots & \ldots & \ldots \\
        0 & 0 & \ldots & 1
    \end{pmatrix}
\end{equation*}
#+end_export

Прямоугольная матрица, все элементы которой равны нулю, называется /нулевой/:
#+begin_export latex
\begin{equation*}
    \underset{m \times n}{\Theta} =
    \begin{pmatrix}
        0 & 0 & \ldots & 0 \\
        0 & 0 & \ldots & 0 \\
        \ldots & \ldots & \ldots & \ldots \\
        0 & 0 & \ldots & 0
    \end{pmatrix}
\end{equation*}
#+end_export

Матрица \(A^T\), у которой по отношению к матрице \(A\) элементы строк и столбцов поменялись местами, называется /транспонированной/ по отношению к \(A\):
#+begin_export latex
\begin{equation*}
    \underset{m \times n}{A} =
    \begin{pmatrix}
        a_{11} & a_{21} & \ldots & a_{m1} \\
        a_{12} & a_{22} & \ldots & a_{m2} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{1n} & a_{2n} & \ldots & a_{nm}
    \end{pmatrix}
    = \underset{m \times n}{A'}.
\end{equation*}
#+end_export

Матрица, для которой справедливо равенство \(A = A^T\) называется /симметричной/.

** Краткая запись различных видов матриц
Перечисленные выше основные виды матриц характеризуются определенными свойствами ее элементов. Введем /символ Кронекера/:
#+begin_export latex
\begin{equation*}
    \delta_{ij} =
    \begin{cases}
        1, \text{ если } i = j, \\
        0, \text{ если } i \neq j
    \end{cases}
\end{equation*}
#+end_export

В таблице ниже приведены условия, с помощью которых можно выразить ранее приведеные свойства для квадратных матриц \(A = (a_{ij}) \; (i,j = \overline{1,n})\).
#+attr_latex: :align |c|c|c|c|
| Условие                      | Название            | Условие             | Название     |
|------------------------------+---------------------+---------------------+--------------|
| \(a_{ij} = 0\) при \(i > j\) | верхняя треугольная | \(a_{ij} = \delta_{ij}\) | единичная    |
| \(a_{ij} = 0\) при \(i < j\) | нижняя треугольная  | \(a_{ij} = 0\)      | нулевая      |
| \(a_{ij} = a_i \delta_{ij}\)      | диагональная        | \(a_{ij} = a_{ji}\) | симметричная |

** Линейные операции
Рассмотрим операции, справедливые для матриц с размерностью \(m \times n\).

*** Сравнение матриц
Две матрицы одинаковых размеров называются равными, если совпадают их элементы с одинаковыми индексами:
\begin{equation*}
    A = B \iff a_{ij} = b_{ij}
\end{equation*}

*** Сложение матриц
Сложение матриц \(A + B\) есть операция нахождения матрицы \(C\), все элементы которой равны попарной сумме всех соответствующих элементов матриц \(A\) и \(B\):
\begin{equation*}
    C = A + B \iff c_{ij} = a_{ij} + b_{ij}
\end{equation*}

Свойства сложения матриц:
- Коммутативность: \(A + B = B + A\)
- Ассоциативность: \(A + B + C = (A + B) + C = A + (B + C)\)
- Сложение с нулевой матрицей: \(A + \theta = \theta + A = A\)
- Существование противоположной матрицы: \(A + A^{-1} = 0\)

*** Умножение матрицы на число
Умножение матрицы \(A\) на число \(\lambda \in \mathcal{K}\) заключается в построении матрицы \(\lambda A = (\lambda a_{ij})\).

Свойства умножения матриц на число:
- Ассоциативность: \((\lambda \beta) A = \lambda (\beta A)\)
- Дистрибутивность: \((\lambda + \beta) A = \lambda A + \beta A\); \quad \(\lambda (A + B) = \lambda A + \lambda B\)
- Умножение на единицу: \(1 \cdot A = A \cdot 1 = A\)

*** Умножение матриц
Умножение матриц — операция вычисления матрицы \(C\), каждый элемент которой равен сумме произведений элементов в соответствующей строке первого множителя и столбце второго:

\begin{equation*}
    c_{ij} = \sum_{k=1}^n a_{ik} b_{kj}
\end{equation*}

Количество столбцов в матрице \(A\) должно совпадать с количеством строк в матрице \(B\). Если матрица \(A\) имеет размерность \(m \times n\), B — \(n \times k\), то размерность их произведения \(AB = C\) есть \(m \times k\).

Свойства умножения матриц:
- Некоммутативность (в общем случае): \(AB \neq BA\)
- Ассоциативность: \((AB)C = A(BC)\)
- Коммутативность при умножении с единичной матрицей: \(AE = EA = A\)
- Дистрибутивность: \((A + B) C = AC + BC\); \quad \(A (B + C) = AB + BC\)
- Ассоциативность и коммутативность умножения на число: \((\lambda A) B = A (\lambda B) = \lambda (AB)\)

** Элементарные преобразования
#+begin_definition
Элементарные преобразования — это такие преобразования матрицы, в результате которых сохраняется эквивалентность матриц.
#+end_definition

Таким образом, элементарные преобразования не изменяют множество решений системы линейных алгебраических уравнений, которую представляет эта матрица. Элементарные операции обратимы. Обозначение \(A \sim B\) указывает на то, что матрица \(A\) может быть получена из матрицы \(B\) путем элементарных преобразований.

Примеры элементарных преобразований строк:
- перестановка местами любых двух строк матрицы;
- умножение любой строки матрицы на константу \(k \neq 0\), при этом определитель матрицы увеличивается в \(k\) раз;
- прибавление к любой строке матрицы другой строки, умноженной на некоторую константу;
- удаление нулевых строк;
- транспонирование.

Аналогично определяются элементарные преобразования столбцов.

** Свойства транспонирования матриц

#+begin_property
\begin{equation*}
    (A^T)^T = A
\end{equation*}
#+end_property

#+begin_proof
\begin{gather*}
    A =
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        a_{21} & a_{22} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{m1} & a_{m2} & \ldots & a_{mn}
    \end{pmatrix}
    \implies
    A^T =
    \begin{pmatrix}
        a_{11} & a_{21} & \ldots & a_{m1} \\
        a_{12} & a_{22} & \ldots & a_{m2} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{1n} & a_{2n} & \ldots & a_{mn}
    \end{pmatrix}
    \implies \\
    \implies
    (A^T)^T =
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        a_{21} & a_{22} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{m1} & a_{m2} & \ldots & a_{mn}
    \end{pmatrix}
    = A
\end{gather*}
#+end_proof


#+begin_property
\begin{equation*}
    (A + B)^T = A^T + B^T
\end{equation*}
#+end_property

#+begin_proof
\begin{equation*}
    A =
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        a_{21} & a_{22} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{m1} & a_{m2} & \ldots & a_{mn}
    \end{pmatrix}
    \qquad
    B =
    \begin{pmatrix}
        b_{11} & b_{12} & \ldots & b_{1n} \\
        b_{21} & b_{22} & \ldots & b_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        b_{m1} & b_{m2} & \ldots & b_{mn}
    \end{pmatrix}
\end{equation*}

\begin{equation*}
    A^T =
    \begin{pmatrix}
        a_{11} & a_{21} & \ldots & a_{m1} \\
        a_{11} & a_{22} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{1n} & a_{2n} & \ldots & a_{mn}
    \end{pmatrix}
    \qquad
    B^T =
    \begin{pmatrix}
        b_{11} & b_{21} & \ldots & b_{m1} \\
        b_{11} & b_{22} & \ldots & b_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        b_{1n} & b_{2n} & \ldots & b_{mn}
    \end{pmatrix}
\end{equation*}

\begin{equation*}
    A + B =
    \begin{pmatrix}
        a_{11} + b_{11} & a_{12} + b_{12} & \ldots & a_{1n} + b_{1n} \\
        a_{21} + b_{21} & a_{22} + b_{22} & \ldots & a_{2n} + b_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{m1} + b_{m1} & a_{m2} + b_{m2} & \ldots & a_{mn} + b_{mn}
    \end{pmatrix}
\end{equation*}

\begin{equation*}
    (A + B)^T =
    \begin{pmatrix}
        a_{11} + b_{11} & a_{21} + b_{21} & \ldots & a_{m1} + b_{m1} \\
        a_{12} + b_{12} & a_{22} + b_{22} & \ldots & a_{m2} + b_{m2} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{1n} + b_{1n} & a_{2n} + b_{2n} & \ldots & a_{mn} + b_{mn}
    \end{pmatrix}
\end{equation*}

\begin{equation*}
    A^T + B^T =
    \begin{pmatrix}
        a_{11} + b_{11} & a_{21} + b_{21} & \ldots & a_{m1} + b_{m1} \\
        a_{12} + b_{12} & a_{22} + b_{22} & \ldots & a_{m2} + b_{m2} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{1n} + b_{1n} & a_{2n} + b_{2n} & \ldots & a_{mn} + b_{mn}
    \end{pmatrix}
\end{equation*}
#+end_proof

#+begin_property
\begin{equation*}
    (\lambda A)^T = \lambda A^T
\end{equation*}
#+end_property

#+begin_proof
\begin{equation*}
    A =
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        a_{21} & a_{22} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{m1} & a_{m2} & \ldots & a_{mn}
    \end{pmatrix}
\end{equation*}

\begin{equation*}
    \lambda A =
    \begin{pmatrix}
        \lambda a_{11} & \lambda a_{12} & \ldots & \lambda a_{1n} \\
        \lambda a_{21} & \lambda a_{22} & \ldots & \lambda a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        \lambda a_{m1} & \lambda a_{m2} & \ldots & \lambda a_{mn}
    \end{pmatrix}
    \qquad
    (\lambda A)^T =
    \begin{pmatrix}
        \lambda a_{11} & \lambda a_{21} & \ldots & \lambda a_{m1} \\
        \lambda a_{12} & \lambda a_{22} & \ldots & \lambda a_{m2} \\
        \ldots & \ldots & \ldots & \ldots \\
        \lambda a_{1n} & \lambda a_{m2} & \ldots & \lambda a_{mn}
    \end{pmatrix}
\end{equation*}

\begin{equation*}
    A^T =
    \begin{pmatrix}
        a_{11} & a_{21} & \ldots & a_{m1} \\
        a_{12} & a_{22} & \ldots & a_{m2} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{1n} & a_{m2} & \ldots & a_{mn}
    \end{pmatrix}
    \qquad
    \lambda A^T =
    \begin{pmatrix}
        \lambda a_{11} & \lambda a_{21} & \ldots & \lambda a_{m1} \\
        \lambda a_{12} & \lambda a_{22} & \ldots & \lambda a_{m2} \\
        \ldots & \ldots & \ldots & \ldots \\
        \lambda a_{1n} & \lambda a_{m2} & \ldots & \lambda a_{mn}
    \end{pmatrix}
\end{equation*}
#+end_proof

#+name: tr-matrix-mul
#+begin_property
\begin{equation*}
    (A \cdot B)^T = B^T \cdot A^T
\end{equation*}
#+end_property

#+begin_proof
\begin{equation*}
    A =
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        a_{21} & a_{22} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{m1} & a_{m2} & \ldots & a_{mn}
    \end{pmatrix}
    \qquad
    B =
    \begin{pmatrix}
        b_{11} & b_{12} & \ldots & b_{1n} \\
        b_{21} & b_{22} & \ldots & b_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        b_{m1} & b_{m2} & \ldots & b_{mn}
    \end{pmatrix}
\end{equation*}

\begin{equation*}
    A^T = C =
    \begin{pmatrix}
        c_{11} & c_{21} & \ldots & c_{m1} \\
        c_{11} & c_{22} & \ldots & c_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        c_{1n} & c_{2n} & \ldots & c_{mn}
    \end{pmatrix}
    \qquad
    B^T = D =
    \begin{pmatrix}
        d_{11} & d_{21} & \ldots & d_{m1} \\
        d_{11} & d_{22} & \ldots & d_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        d_{1n} & d_{2n} & \ldots & d_{mn}
    \end{pmatrix}
    \qquad
    \begin{cases}
        a_{ij} = c_{ji} \\
        b_{\alpha \beta} = d_{\beta \alpha}
    \end{cases}
\end{equation*}

\begin{equation*}
    A \cdot B = F =
    \begin{pmatrix}
        f_{11} & f_{21} & \ldots & f_{m1} \\
        f_{11} & f_{22} & \ldots & f_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        f_{1n} & f_{2n} & \ldots & f_{mn}
    \end{pmatrix}
    \qquad
    B^T \cdot A^T = G =
    \begin{pmatrix}
        g_{11} & g_{21} & \ldots & g_{m1} \\
        g_{11} & g_{22} & \ldots & g_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        g_{1n} & g_{2n} & \ldots & g_{mn}
    \end{pmatrix}
\end{equation*}

\begin{equation*}
    g_{ji} =
    \sum_{\alpha = 1}^k d_{j \alpha} c_{\alpha i} =
    \sum_{\alpha = 1}^k b_{\alpha j} a_{i \alpha} =
    \sum_{\alpha = 1}^k a_{i \alpha} b_{\alpha j} =
    f_{ij}
\end{equation*}

\begin{equation*}
    G = F^T \implies (A \cdot B)^T = B^T \cdot A^T
\end{equation*}
#+end_proof

** Вычисление определителей
#+name: det-decomposition
#+attr_latex: :options [о раздложении определителя]
#+begin_theorem
Определителем порядка \(n\), соответствующим квадратной матрице порядка \(n\), называется число, равное
\[
    \det A = \sum_{i = 1}^n a_{ij} A_{ij} = \sum_{j = 1}^n a_{ij} A_{ij} = \sum_{i = 1}^n (-1)^{i + j} a_{ij} M_{ij}.
\]
где
- \(i, j \in (\overline{1,n})\);
- \(A_{ij}\) — соответствующее алгебраическое дополнение \(a_{ij}\);
- \(M_{ij}\) — соответствующий минор элемента \(a_{ij}\).
#+end_theorem

#+begin_proof
Опираясь на основные свойства определителей, выпишем цепочку равенств:
\begin{gather*}
    \det A =
    \begin{vmatrix}
        a_{11} & \ldots & a_{1j} & \ldots & a_{1n} \\
        a_{21} & \ldots & a_{2j} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{n1} & \ldots & a_{nj} & \ldots & a_{nn} \\
    \end{vmatrix}
    = \\ =
    \begin{vmatrix}
        a_{11} & \ldots & a_{1j} & \ldots & a_{1n} \\
        a_{21} & \ldots & 0 & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{n1} & \ldots & 0 & \ldots & a_{nn} \\
    \end{vmatrix}
    +
    \begin{vmatrix}
        a_{11} & \ldots & 0 & \ldots & a_{1n} \\
        a_{21} & \ldots & a_{2j} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{n1} & \ldots & 0 & \ldots & a_{nn} \\
    \end{vmatrix}
    + \ldots +
    \begin{vmatrix}
        a_{11} & \ldots & 0 & \ldots & a_{1n} \\
        a_{21} & \ldots & 0 & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{n1} & \ldots & a_{nj} & \ldots & a_{nn} \\
    \end{vmatrix}
    = \\ =
    \sum_{i = 1}^n
    \begin{vmatrix}
        a_{11} & \ldots & a_{1j - 1} & 0 & a_{1j + 1} & \ldots & a_{1n} \\
        \ldots & \ldots & \ldots & \ldots & \ldots & \ldots \\
        a_{i1} & \ldots & a_{ij - 1} & a_{ij} & a_{ij + 1} & \ldots & a_{in} \\
        \ldots & \ldots & \ldots & \ldots & \ldots & \ldots \\
        a_{n1} & \ldots & a_{nj - 1} & 0 & a_{nj + 1} & \ldots & a_{nn} \\
    \end{vmatrix}
    = \\ =
    \sum_{i = 1}^n
    \begin{vmatrix}
        a_{ij} & a_{i1} & \ldots & a_{ij - 1} & a_{ij + 1} & \ldots & a_{in} \\
        0 & a_{11} & \ldots & a_{1j - 1} & a_{1j + 1} & \ldots & a_{1n} \\
        \ldots & \ldots & \ldots & \ldots & \ldots & \ldots & \ldots & \\
        0 & a_{i - 1,1} & \ldots & a_{i - 1,j - 1} & a_{i - 1,j + 1} & \ldots & a_{i - 1,n} \\
        0 & a_{i + 1,1} & \ldots & a_{i + 1,j - 1} & a_{i + 1,j + 1} & \ldots & a_{i + 1,n} \\
        \ldots & \ldots & \ldots & \ldots & \ldots & \ldots & \ldots & \\
        0 & a_{n1} & \ldots & a_{nj - 1} & a_{nj + 1} & \ldots & a_{nn}
    \end{vmatrix}
    =
    \sum_{i = 1}^n (-1)^{i + j} a_{ij} M_{ij}.
\end{gather*}
Таким образом, часть теоремы доказана. Положим теперь \(A^T = (a'_{ij})\), где \(a'_{ji} = a_{ij}\). Заметим, что соответствующим элементу \(a'_{ji}\) в \(\det A^T\) будет \(M'_{ji} = M_{ij}\). Как было показано выше,
\[
    \det A = \det A^T = \sum_{j = 1}^n (-1)^{j + i} a'_{ji} M'_{ji} = \sum_{j = 1}^n (-1)^{i + j} a_{ij} M_{ij}.
\]
#+end_proof

** Присоединенная матрица
#+begin_definition
Присоединенная матрица \(A^c\) — это транспонированная матрица алгебраических дополнений \(A_{ij}\) элементов \(a_{ij}\) матрицы \(A\):
\begin{equation*}
    A^c =
    \begin{pmatrix}
        A_{11} & A_{21} & \ldots & A_{n1} \\
        A_{12} & A_{22} & \ldots & A_{n2} \\
        \ldots & \ldots & \ldots & \ldots \\
        A_{1n} & A_{2n} & \ldots & A_{nn}
    \end{pmatrix};
\end{equation*}
#+end_definition

#+name: det-cancellation
#+attr_latex: :options [Аннулирование]
#+begin_theorem
Сумма произведений  элементов любой строки (или столбца) на алгебраические дополнения элементов другой строки (столбца) равна нулю:
\begin{equation*}
    \sum_{k = 1}^n a_{ik} A_{jk} = 0, \quad (i \neq j);
    \qquad
    \sum_{k = 1}^n a_{ki} A_{kj} = 0, \quad (i \neq j).
\end{equation*}
#+end_theorem

#+begin_proof
Рассмотрим вспомогательную матрицу \(A'\), полученную из матрицы \(A\), заменой \(j\)-ой строки \(i\)-ой строкой:
\begin{equation*}
    A =
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{i1} & a_{i2} & \ldots & a_{in} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{j1} & a_{j2} & \ldots & a_{jn} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{n1} & a_{n2} & \ldots & a_{nn}
    \end{pmatrix};
    \qquad
    A' =
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{i1} & a_{i2} & \ldots & a_{in} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{j1} & a_{j2} & \ldots & a_{jn} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{n1} & a_{n2} & \ldots & a_{nn}
    \end{pmatrix}.
\end{equation*}
\begin{equation*}
    \det A' = \sum_{k = 1}^n a_{jk} A'_{jk} = \sum_{k = 1}^n a_{ik} A'_{jk}.
\end{equation*}
Заметим, что алгебраическое дополнение элемента некоторой строки не зависит от элементов этой строки (поскольку при вычислении алгебраического дополнения эта строка просто вычеркивается). Однако матрицы \(A\) и \(A'\) отличаются только \(j\)-ой строкой, следовательно, \(A_{jk} = A'_{jk}\). Тогда
\begin{equation*}
   \det A' = \sum_{k = 1}^n a_{ik} A_{jk}.
\end{equation*}
Поскольку матрица \(A'\) имеет две одинаковые строки, ее определитель равен нулю. Аналогично доказывается случай со столбцами.
#+end_proof

** Невырожденная матрица
#+begin_definition
Невырожденная матрица — это квадратная матрица, определитель которой отличен от нуля. В противном случае матрица называется вырожденной.
#+end_definition

** Обратная матрица

#+begin_definition
Обратная матрица — это такая матрица \(A^{-1}\), при умножении которой на исходную матрицу \(A\) получается единичная матрица \(E\):

\begin{equation*}
    AA^{-1} = A^{-1}A = E.
\end{equation*}
#+end_definition

*** Свойства обратной матрицы

#+begin_property
\begin{equation*}
    \det A^{-1} = (\det A)^{-1}
\end{equation*}
#+end_property

#+begin_proof
\begin{equation*}
    \det E = \det (A^{-1} A) = \det A^{-1} \det A
    \quad \implies \quad
    \det A^{-1} = \frac{\det E}{\det A} = \frac{1}{\det A} = (\det A)^{-1}.
\end{equation*}
#+end_proof

#+begin_property
\begin{equation*}
    (AB)^{-1} = B^{-1}A^{-1}
\end{equation*}
#+end_property

#+begin_proof
\begin{gather*}
    \begin{cases}
        B^{-1} A^{-1} AB = B^{-1} E B = E \\
        AB B^{-1} A^{-1} = A E A^{-1} = E
    \end{cases}
    \implies
    (AB)^{-1} = B^{-1} A^{-1}.
\end{gather*}
#+end_proof

#+begin_property
\begin{equation*}
    (A^T)^{-1} = (A^{-1})^T
\end{equation*}
#+end_property

#+begin_proof
Воспользуемся [[tr-matrix-mul][одним из свойств]] транспонированных матриц
\begin{equation*}
    \begin{cases}
        (A^{-1})^T A^T = (A^{-1} A)^T = E^T = E \\
        A^T (A^{-1})^T = (A A^{-1})^T = E^T = E
    \end{cases}
    \implies
    (A^{-1})^T = A^T.
\end{equation*}
#+end_proof

#+begin_property
\begin{equation*}
    (A^{-1})^{-1} = A
\end{equation*}
#+end_property

#+begin_proof
\begin{gather*}
    (A^{-1})^{-1} = A
    \quad
    \implies
    \quad
    (A^{-1})^{-1} A^{-1} A = A
    \quad
    \stackrel{2 \; \text{св.}}{\implies}
    \quad
    (A A^{-1})^{-1} A = A
    \quad
    \implies \\
    \implies
    \quad
    (A A^{-1})^{-1} A = A
    \quad
    \implies
    \quad
    E^{-1} A = A
    \quad
    \implies
    \quad
    A = A
\end{gather*}
#+end_proof

#+begin_property
\begin{equation*}
    (\lambda A)^{-1} = \lambda^{-1} A^{-1}
\end{equation*}
#+end_property

#+begin_proof
\begin{equation*}
    \begin{cases}
        \lambda A \lambda^{-1} A^{-1} = 1E = E \\
        \lambda^{-1} A^{-1} \lambda A = 1E = E
    \end{cases}
    \implies
    (\lambda A)^{-1} = \lambda^{-1} A^{-1}.
\end{equation*}
#+end_proof

*** Теоремы

#+begin_theorem
Для всякой невырожденной матрицы \(A\) существует обратная матрица \(A^{-1}\) и притом только одна.
#+end_theorem

#+begin_proof
Сначала докажем существование обратной матрицы. Пусть нам дана следующая матрица \(A\), определитель которой не равен нулю:
\begin{equation*}
    A =
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        a_{21} & a_{22} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{i1} & a_{i2} & \ldots & a_{in} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{n1} & a_{n2} & \ldots & a_{nn}
    \end{pmatrix}
\end{equation*}

Для этой матрицы построим [[*Присоединенная матрица][присоединенную матрицу]]:
\begin{equation*}
    A^c =
    \begin{pmatrix}
        A_{11} & A_{21} & \ldots & A_{n1} \\
        A_{12} & A_{22} & \ldots & A_{n2} \\
        \ldots & \ldots & \ldots & \ldots \\
        A_{1n} & A_{2n} & \ldots & A_{nn}
    \end{pmatrix}
\end{equation*}

Перемножим матрицы \(A\) и \(A^c\):
\begin{gather*}
    A^c A =
    \begin{pmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        a_{21} & a_{22} & \ldots & a_{2n} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{i1} & a_{i2} & \ldots & a_{in} \\
        \ldots & \ldots & \ldots & \ldots \\
        a_{n1} & a_{n2} & \ldots & a_{nn}
    \end{pmatrix}
    \begin{pmatrix}
        A_{11} & A_{21} & \ldots & A_{n1} \\
        A_{12} & A_{22} & \ldots & A_{n2} \\
        \ldots & \ldots & \ldots & \ldots \\
        A_{1n} & A_{2n} & \ldots & A_{nn}
    \end{pmatrix}
    = \\ =
    \setlength{\cellspacetoplimit}{3pt}
    \setlength{\cellspacebottomlimit}{3pt}
    \begin{pmatrix}
        \sum_{k = 1}^n A_{k1} a_{k1} & \sum_{k = 1}^n A_{k1} a_{k2} & \ldots & \sum_{k = 1}^n A_{k1} a_{kn} \\
        \sum_{k = 1}^n A_{k2} a_{k1} & \sum_{k = 1}^n A_{k2} a_{k2} & \ldots & \sum_{k = 1}^n A_{k2} a_{kn} \\
        \ldots & \ldots & \ldots & \ldots \\
        \sum_{k = 1}^n A_{kn} a_{k1} & \sum_{k = 1}^n A_{kn} a_{k2} & \ldots & \sum_{k = 1}^n A_{kn} a_{kn} \\
    \end{pmatrix}
\end{gather*}

По [[det-decomposition][теореме о разложении определителя]] и [[det-cancellation][теореме аннулирования]]:
\begin{equation*}
    \begin{cases}
        i = k \implies \sum_{k = 1}^n a_{ik} A_{jk} = \det A \\
        i \neq k \implies \sum_{k = 1}^n a_{ik} A_{jk} = 0
    \end{cases}
\end{equation*}

Тогда получим, что
\begin{equation*}
    A^c A =
    \begin{pmatrix}
        \det A & 0 & \ldots & 0 \\
        0 & \det A & \ldots & 0 \\
        \ldots & \ldots & \ldots & \ldots \\
        0 & 0 & \ldots & \det A \\
    \end{pmatrix}
    = \det A
    \begin{pmatrix}
        1 & 0 & \ldots & 0 \\
        0 & 1 & \ldots & 0 \\
        \ldots & \ldots & \ldots & \ldots \\
        0 & 0 & \ldots & 1 \\
    \end{pmatrix}
    = E \det A.
\end{equation*}

Значит обратная матрица равна
\begin{equation*}
    A^{-1} = \frac{A^c}{\det A}.
\end{equation*}

Аналогично доказывается случай \(A A^c\), Теперь докажем единственность обратной матрицы. Предположим, что существует две обратные матрицы: \(A^{-1}\) и \(\tilde{A}\). Тогда
\begin{equation*}
    \begin{cases}
        AA^{-1} = A^{-1} A = E \\
        A\tilde{A} = \tilde{A} A = E
    \end{cases}
    \implies
    A^{-1} A \tilde{A} =
    \begin{cases}
        A^{-1} (A\tilde{A}) = A^{-1} E = A^{-1} \\
        (A^{-1} A) \tilde{A} = E \tilde{A} = \tilde{A}
    \end{cases}
    \implies
    A^{-1} = \tilde{A}.
\end{equation*}

Результат противоречит исходному предположению о существовании двух обратных матриц.
#+end_proof

** Норма матрицы
#+begin_definition
Нормой матрицы \(A \in \mathcal{K}^{m \times n}\) (обычно \(\mathcal{K} = \mathbb{R}\) или \(\mathcal{K} = \mathbb{C}\)) понимается неотрицательное число \(\|A\|\), удовлетворяющее следующим аксиомам:
1. \(\|A\| \geq 0\);
2. \(\|\lambda A\| = |\lambda| \|A\|\), где \(\lambda \in \mathbb{R}\) или \(\lambda \in \mathbb{C}\);
3. \(\|A + B\| \leq \|A\| + \|B\|\), где \(A\) и \(B\) — матрицы, допускающие сложение;
4. \(\|AB\| \leq \|A\| \|B\|\), где \(A\) и \(B\) — матрицы, допускающие умножение.
#+end_definition

#+begin_definition
Норма \(\|A\|\) называется /мультипликативной/, если выполняются все 4 аксиомы, и /аддитивной/, если выполняются первые 3 аксиомы.
#+end_definition

#+begin_definition
Если матрица удовлетворяет условию
\[
    \|\lambda A\| \leq |\lambda| \|A\|,
\]
то такая норма называются /согласованной/ с нормой вектора.
#+end_definition

Определим некоторые наиболее употребительные на практике матричные нормы:
- Евклидова норма или норма Фробениуса:
  \[
    \|A\|_E = \sqrt{\sum_{i = 1}^m \sum_{j = 1}^n a_{ij}^2}.
  \]
- Столбцовая норма:
  \[
    \|A\|_1 = \max_{1 \leq j \leq n} \sum_{i = 1}^m |a_{ij}|.
  \]
- Строковая форма:
  \[
    \|A\|_\infty = \max_{1 \leq i \leq m} \sum_{j = 1}^n |a_{ij}|.
  \]
- Спектральная норма:
  \[
    \|A\|_2 = \sqrt{\max_i(\sigma_i)},
  \]
  где \(\sigma_i\) — собственные значения симметричной матрицы \(A^T A\).

* Список задач :noexport:
** TODO Дополнить ранг матрицы
** TODO Линейная независимость
